batch_size: 32
learning_rate: 1.0e-05
momentum: null
num_days_for_predict: 60
num_days_to_predict: 1
num_workers: 1
optimizer: !!python/name:torch.optim.rmsprop.RMSprop ''
target: Microsoft
train_size: 0.8
